<!--

    Gaia Data Processing and Analysis Consortium (DPAC) 
    Co-ordination Unit 9 Work Package 930
    
    (c) 2005-2025 Gaia DPAC
    
    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>.
    -->

The science exploitation platform currently hosts the following data sets:

* The full set of Gaia DR3 tables including the main source catalogue (e.g. `gaiadr3.gaia_source`) and all other astrophysical parameter and spectroscopy data presented in the same name space as in the Gaia archive;
* The Gaia EDR3 source catalogue (direct copies of `gaiaedr3.gaia_source` from the Gaia archive) along with Bailer-Jones distances corresponding to `gaiaedr3.gaiaedr3_distance`; and
* Best neighbour tables for PanSTARRS DR1, 2MASS PSC and ALLWISE (again, directly mirrored from the corresponding tables in the Gaia archive under the gaiaedr3 / gaiadr3 namespace) along with the original records from the 2MASS PSC and ALLWISE catalogues, and Object Thin / Object Mean columns from PanSTARRS DR1 (respectively 2MASS, ALLWISE and PS1 hereafter) where a best neighbour is available.

These are presented as queryable resources as demonstrated in the following cells and subsequent notebooks.  Each cell can be run by pressing the "Run" icon above; hover over other icons to see more options, e.g. to clear current output.

In [1]:
from dask.distributed import Client

In [2]:
c = Client('tcp://simple-scheduler.dask-operator.svc.cluster.local:8786')

/usr/local/lib/python3.10/site-packages/distributed/client.py:1612: VersionMismatchWarning: Mismatched versions found

+---------+-----------------+-----------------+-----------------+
| Package | Client          | Scheduler       | Workers         |
+---------+-----------------+-----------------+-----------------+
| lz4     | 4.4.4           | 4.3.3           | 4.3.3           |
| numpy   | 2.2.6           | 2.2.2           | 2.2.2           |
| python  | 3.10.16.final.0 | 3.10.12.final.0 | 3.10.12.final.0 |
| toolz   | 1.0.0           | 0.12.0          | 0.12.0          |
| tornado | 6.4.1           | 6.4.2           | 6.4.2           |
+---------+-----------------+-----------------+-----------------+
  warnings.warn(version_module.VersionMismatchWarning(msg[0]["warning"]))

In [3]:
print(c)

<Client: 'tcp://192.168.63.173:8786' processes=10 threads=60, memory=250.00 GiB>

In [ ]:
import dask.dataframe as dd
import os
from pathlib import Path

ddf = dd.read_parquet(Path(os.environ['DASK_DATA_PATH_GAIA_DR3_SSD']).joinpath('GDR3_GAIA_SOURCE/')).set_index("source_id")

# show the first 20 records from the Gaia DR3 source catalogue
ddf.head(20)

,solution_id,designation,random_index,ref_epoch,ra,ra_error,dec,dec_error,parallax,parallax_error,...,azero_gspphot,azero_gspphot_lower,azero_gspphot_upper,ag_gspphot,ag_gspphot_lower,ag_gspphot_upper,ebpminrp_gspphot,ebpminrp_gspphot_lower,ebpminrp_gspphot_upper,libname_gspphot
source_id,,,,,,,,,,,,,,,,,,,,,
4295806720,1636148068921376768,Gaia DR3 4295806720,545300884,2016.0,44.996155,0.101618,0.005615,0.101334,0.354331,0.122664,...,0.0064,0.0016,0.0176,0.0052,0.0013,0.0143,0.0028,0.0007,0.0078,MARCS
34361129088,1636148068921376768,Gaia DR3 34361129088,894504938,2016.0,45.004320,0.097320,0.021048,0.101753,3.235017,0.120450,...,0.7643,0.7292,0.7975,0.5050,0.4815,0.5273,0.3096,0.2956,0.3228,MARCS
38655544960,1636148068921376768,Gaia DR3 38655544960,1757259052,2016.0,45.004978,0.017885,0.019880,0.018772,3.139170,0.022347,...,0.2345,0.1840,0.2516,0.1820,0.1425,0.1955,0.0961,0.0752,0.1032,MARCS
309238066432,1636148068921376768,Gaia DR3 309238066432,327609758,2016.0,44.995037,0.322039,0.038152,0.283505,1.383150,0.367907,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>
343597448960,1636148068921376768,Gaia DR3 343597448960,1791600903,2016.0,44.963896,0.117176,0.043595,0.109004,0.196148,0.133464,...,0.0085,0.0024,0.0204,0.0065,0.0018,0.0158,0.0035,0.0009,0.0084,PHOENIX
515396233856,1636148068921376768,Gaia DR3 515396233856,791118203,2016.0,44.998327,0.325203,0.066333,0.325257,0.242394,0.374324,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>
549755818112,1636148068921376768,Gaia DR3 549755818112,1176142027,2016.0,45.048282,0.027804,0.048254,0.026500,1.583477,0.034425,...,0.3668,0.3498,0.3862,0.2886,0.2750,0.3042,0.1550,0.1476,0.1633,MARCS
828929527040,1636148068921376768,Gaia DR3 828929527040,602360354,2016.0,45.023620,0.054348,0.068419,0.057793,1.203095,0.066816,...,0.0405,0.0079,0.0907,0.0304,0.0059,0.0684,0.0162,0.0031,0.0363,PHOENIX
927713095040,1636148068921376768,Gaia DR3 927713095040,1643621005,2016.0,45.026727,0.303744,0.081699,0.322892,-0.122728,0.368763,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>
966367933184,1636148068921376768,Gaia DR3 966367933184,1173244990,2016.0,45.039080,0.401012,0.086855,0.397626,1.467697,0.459791,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>
1099511693312,1636148068921376768,Gaia DR3 1099511693312,756765581,2016.0,44.966546,0.238244,0.046309,0.219186,-0.344778,0.270079,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>
1275606125952,1636148068921376768,Gaia DR3 1275606125952,1616763991,2016.0,44.993271,0.044207,0.076334,0.037414,0.629650,0.048079,...,0.0040,0.0009,0.0100,0.0032,0.0007,0.0081,0.0017,0.0004,0.0043,PHOENIX
1340029955712,1636148068921376768,Gaia DR3 1340029955712,1491207483,2016.0,44.969077,0.096023,0.084425,0.083741,0.415616,0.105003,...,0.0348,0.0069,0.2168,0.0270,0.0053,0.1699,0.0145,0.0028,0.0910,PHOENIX
1340029956224,1636148068921376768,Gaia DR3 1340029956224,1752449056,2016.0,44.978462,0.158328,0.092579,0.138827,0.311065,0.171886,...,0.0057,0.0014,0.0160,0.0043,0.0010,0.0121,0.0023,0.0005,0.0065,PHOENIX
1374389600384,1636148068921376768,Gaia DR3 1374389600384,866663434,2016.0,44.932802,0.134052,0.064809,0.116465,1.765055,0.149890,...,0.4993,0.4523,0.5627,0.3329,0.3016,0.3757,0.1986,0.1802,0.2236,MARCS
1511828647680,1636148068921376768,Gaia DR3 1511828647680,1049362040,2016.0,44.952652,0.217552,0.084952,0.196439,-0.097993,0.243493,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>
1619203481984,1636148068921376768,Gaia DR3 1619203481984,955831289,2016.0,44.951158,0.114892,0.105312,0.092665,1.717299,0.117083,...,0.9776,0.9422,1.0066,0.6520,0.6285,0.6718,0.3940,0.3805,0.4049,MARCS
1653563247744,1636148068921376768,Gaia DR3 1653563247744,991970824,2016.0,44.996062,0.043180,0.084918,0.037708,0.301315,0.047155,...,0.2924,0.2672,0.3159,0.2512,0.2293,0.2716,0.1379,0.1259,0.1491,MARCS
1683627775360,1636148068921376768,Gaia DR3 1683627775360,1045293537,2016.0,45.013788,0.341246,0.087734,0.312282,2.937680,0.383909,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>
1717987078400,1636148068921376768,Gaia DR3 1717987078400,71332990,2016.0,44.983097,0.160681,0.096406,0.144907,2.736716,0.178418,...,0.0844,0.0351,0.1558,0.0525,0.0218,0.0971,0.0365,0.0152,0.0672,MARCS

Column descriptions for `gaia_source` are browsable within the Gaia archive ADQL search tree-view, and also (for Gaia DR3 for example) [online](https://gea.esac.esa.int/archive/documentation/GDR3/Gaia_archive/chap_datamodel/sec_dm_main_source_catalogue/ssec_dm_gaia_source.html), as are the [best neighbour table columns](https://gea.esac.esa.int/archive/documentation/GDR3/Gaia_archive/chap_datamodel/sec_dm_cross-matches/). For the "external" catalogues the column sets can be browsed as follows (click on each to follow the links):

* [2MASS PSC](https://irsa.ipac.caltech.edu/data/2MASS/docs/releases/allsky/doc/sec2_2a.html "2MASS point-source catalogue column details");
* [ALLWISE](https://wise2.ipac.caltech.edu/docs/release/allwise/expsup/sec2_1a.html "ALLWISE catalogue column details");
* [PS1 OTMO](https://outerspace.stsci.edu/display/PANSTARRS/PS1+MeanObjectView+table+fields "PS1 DR1 object-thin object-mean catalogue column details") (note that column names follow the Gaia archive convention of all lower-case with underscore separators rather than the original CamelCase).

It is important to note that the best neighbour tables should not be used as a proxy for the original external survey datasets: only those records that are the best neighbour to one or more Gaia sources are included here. If you wish to query and analyse one or other of those catalogues in isolation, this is not the facility to use! The phrase "one or more" is also noteworthy: because of the way the Gaia cross-matches have been derived any one external catalogue source can be the best neighbour to more than one Gaia source. Please consult the [Gaia cross-match documentation on-line](https://gea.esac.esa.int/archive/documentation/GDR3/Catalogue_consolidation/chap_crossmatch/) to familiarise yourself with the details.

Column details can also be examined within the notebook by defining a data frame object against any table then echoing the schema; subsequent cells demonstrate some simple queries:

In [5]:
ddf.dtypes

solution_id                         int64
designation               string[pyarrow]
random_index                        int64
ref_epoch                         float64
ra                                float64
                               ...
ag_gspphot_upper                  float32
ebpminrp_gspphot                  float32
ebpminrp_gspphot_lower            float32
ebpminrp_gspphot_upper            float32
libname_gspphot           string[pyarrow]
Length: 151, dtype: object

In [6]:
# subsetting is easy
ddf.loc[:, ["ra", "dec"]]

Dask DataFrame Structure:
                          ra      dec
npartitions=2048
4295806720           float64  float64
21479132452992           ...      ...
...                      ...      ...
6917525389805002368      ...      ...
6917528997577384320      ...      ...
Dask Name: getitem, 3 expressions
Expr=(SetIndex(frame=ReadParquetFSSpec(c3c076c), _other='source_id', options={}))[['ra', 'dec']]

In [7]:
tmass = dd.read_parquet("/mnt/scratch/region-partitioned/TMASS_PSC_BEST_NEIGHBOURS_REGION_PARTITIONED", index="source_id")

In [8]:
tmass.head()

,original_ext_source_id,angular_distance,xm_flag,clean_tmass_psc_xsc_oid,number_of_neighbours,number_of_mates,ra,dec,err_maj,err_min,...,dist_opt,phi_opt,b_m_opt,vr_m_opt,nopt_mchs,ext_key,scan_key,coadd_key,coadd,region
source_id,,,,,,,,,,,,,,,,,,,,,
29858612862592,03002052+0026464,0.131110,8,294669064,1,0,45.085517,0.446242,0.15,0.08,...,0.2,163.0,17.799999,16.799999,1,NaN,61142,1406265,256,NaN
32817845957120,02593260+0029554,0.069805,16,294828601,1,0,44.885841,0.498748,0.14,0.09,...,0.3,177.0,18.600000,17.299999,1,2260658.0,61140,1406218,245,NaN
33122788020096,03000441+0028470,0.361921,16,294770732,1,0,45.018375,0.479733,0.26,0.22,...,NaN,NaN,NaN,NaN,0,NaN,61141,1406222,21,NaN
77863462880768,02583846+0031025,0.081568,8,294885634,1,0,44.660288,0.517385,0.08,0.06,...,4.6,87.0,16.200001,14.100000,1,NaN,61508,1414682,245,NaN
630535558946688,03063009+0158056,0.128137,8,299269009,1,0,46.625376,1.968230,0.14,0.12,...,NaN,NaN,NaN,NaN,0,NaN,66133,1521052,186,NaN